package ru.shaldnikita.starter.web.forms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TwinColSelect;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserEditFormDesign extends FormLayout {
    protected TextField firstName;
    protected TextField lastName;
    protected TextField login;
    protected TextField password;
    protected TextField email;
    protected ComboBox<String> role;
    protected TwinColSelect<String> groups;

    public UserEditFormDesign() {
        Design.read(this);
    }

}
