package ru.shaldnikita.starter.web.view.common;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import ru.shaldnikita.starter.web.components.EditForm;
import org.vaadin.teemusa.gridextensions.SelectGrid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CrudViewDesign extends VerticalLayout {
    protected HorizontalLayout top;
    protected Button filter;
    protected Button add;
    protected HorizontalLayout bot;
    protected SelectGrid grid;
    protected EditForm editForm;
    protected HorizontalLayout paging;
    protected CssLayout totalRecordsInfo;
    protected Label totalRecords;
    protected Label totalRecordsCount;
    protected HorizontalLayout pagingButtons;
    protected CssLayout prev;
    protected Button firstPage;
    protected Button prevPage;
    protected NativeSelect<Integer> recordsPerPage;
    protected CssLayout next;
    protected Button nextPage;
    protected Button lastPage;

    public CrudViewDesign() {
        Design.read(this);
    }

}
